name: Publish Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
  schedule:
    # Every day at 05:00 EST (10:00 UTC)
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        run: |
          cd .scripts

          if [ "${LOG_LEVEL}" == "debug" ]; then
            sh -x ./package.sh
          else
            sh ./package.sh
          fi
        env:
          AUTHOR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWER_TOKEN: ${{ secrets.AFRESHY_PAT }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
