name: Publish Release

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 */2 * * *' # Every 2 hours

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        run: cd .scripts && sh ./package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWER_TOKEN: ${{ secrets.REVIEWER_TOKEN }}
